application: absolutelysuperlist
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  expiration: 0d

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
